script:
- npm test
language: node_js
node_js:
- '0.10'
before_install:
- gem install sass --version 3.3
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && make deploy
